# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[migrations_directory]
dir = "/tukosmo/src/core/shared/infrastructure/diesel_orm/migration"

[print_schema]
custom_type_derives = ["diesel::query_builder::QueryId"]
file = "/tukosmo/src/core/shared/infrastructure/diesel_orm/schema.rs"
